### ISSUE TITLE
Incorrect output of "Date Added"

### ISSUE THREAD

**Issue by linxule** [argenos/zotero-mdnotes#13] opened 2020-09-10 14:15 UTC
With the latest update, the outputs of "Date Added" are incorrect that:
1.  "2020-01-23" becomes "2020-00-23"
2. "2020-02-01" becomes "2020-01-01"

**Comment by argenos** [comment] 2020-09-10 15:33
Are these the dates of the Zotero item or the ones from the markdown files?

**Comment by linxule** [comment] 2020-09-10 17:27
Of the Zotero items. I have attached an example here
<img width="821" alt="20200910182655@2x" src="https://user-images.githubusercontent.com/43122877/92772046-487b3e80-f393-11ea-9cb3-bedb81d7e5cb.png">
<img width="346" alt="20200910182705@2x" src="https://user-images.githubusercontent.com/43122877/92772053-4a450200-f393-11ea-8121-44923c74e99c.png">

**Comment by argenos** [comment] 2020-09-10 20:02
That's strange... I'm not really modifying the dates of the item or the PDF attachments. The only date which could have been affected is the `Modified date` of the markdown files to reflect the last time they were exported. 

Does this happen immediately after export?

**Comment by hwongbaul** [comment] 2020-09-11 03:19
I had a check and report the same question:
![image](https://user-images.githubusercontent.com/8535390/92851739-7fe3fc80-f420-11ea-8b89-a2963634b4ec.png)
![image](https://user-images.githubusercontent.com/8535390/92851752-83778380-f420-11ea-809f-6c5c9fc06eaf.png)

It happens right after my first export.

**Comment by linxule** [comment] 2020-09-11 09:56
Same as above. It happened right after export with the most recent update.

**Comment by argenos** [comment] 2020-09-11 10:53
It might have something to do with the locale. Could you try with these? You'll have to change the extension from `.zip` to `.xpi`. 
- This one changes the format used in `Modified date` [mdnotes-0.0.7-fx.zip](https://github.com/argenos/zotero-mdnotes/files/5208439/mdnotes-0.0.7-fx.zip)
- This one removes the `Modified date` update alltogether: [mdnotes-0.0.7-fx-2.zip](https://github.com/argenos/zotero-mdnotes/files/5208448/mdnotes-0.0.7-fx-2.zip)

**Comment by hwongbaul** [comment] 2020-09-14 06:19
Hi, argenos. Thanks for your work. I try the first `mdnotes-0.0.7-fx.zip`and it turns out that the problem in `Date added` filed persists.

**Comment by argenos** [comment] 2020-09-14 08:30
I'm having a hard time reproducing this. Just to make sure ... After installing the new version you need to try it with a new item, it won't fix the date of the previous item. I would suggest adding a dummy item and manually creating a note, and then exporting.
Did you also try the 2nd file?

**Comment by linxule** [comment] 2020-09-15 12:16
@argenos 
I tried both files with two different dummy items. The issue seems to be unresolved. 
<img width="648" alt="20200915131256@2x" src="https://user-images.githubusercontent.com/43122877/93209148-96a68e00-f755-11ea-952a-d5d84432bb52.png">
<img width="655" alt="20200915131451@2x" src="https://user-images.githubusercontent.com/43122877/93209154-97d7bb00-f755-11ea-8771-cc2ce8a11049.png">

**Comment by PhilipMottershead** [comment] 2021-02-09 19:05
I'm getting this issue

**Comment by PhilipMottershead** [comment] 2021-02-09 19:06
![image](https://user-images.githubusercontent.com/10285031/107414370-d0fc3780-6b09-11eb-80a7-da96d6fe92b3.png)
![image](https://user-images.githubusercontent.com/10285031/107414413-deb1bd00-6b09-11eb-9fd3-b2e02d06ba24.png)

**Comment by PhilipMottershead** [comment] 2021-02-09 19:55
So I found the issue it a index starts from 0 error

**Closed** 2024-10-18 11:27 UTC
Labels: bug, awaiting user feedback
