### ISSUE TITLE
Can't  automatically use citekey as mdnotes' title with the latest version of BetterBibTex

### ISSUE THREAD

**Issue by lrcxx** [argenos/zotero-mdnotes#224] opened 2023-10-24 09:21 UTC
**Describe the bug**
Can't create mdnotes using citekey as mdnotes' title. Only can create mdnotes when don't use citekey as title. 
This bug happened when BetterBibTex was updated to the latest version. The citekey seems alright in the paper's info, so it may be the calling procedure that go wrong.

**To Reproduce**
1. Go to "Tools ->Mdnotes preferences", turn on the option"Use the item's citekey as title"
2. Right click the paper.
3. Go to "Mdnotes->Create Mdnotes file"
4. **Nothing will happen** as there should be a file-saving window

**Expected behavior**
I would really appreciate it if this issue related to BetterBibTex recent update could be solved soon. 

**Screenshots**
![image](https://github.com/argenos/zotero-mdnotes/assets/100119811/bf831e43-e033-4507-9c84-42c428d1723f)
![image](https://github.com/argenos/zotero-mdnotes/assets/100119811/606f7aaa-33e0-4933-b0b4-74e2408bbe99)
It should show a window like this but it wasn't.
![image](https://github.com/argenos/zotero-mdnotes/assets/100119811/97337c11-1bbb-486b-aa69-4c57808e10a6)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Zotero version: [v6.0.27]
 - Mdnotes version: [v0.2.3]
 - Zotfile version: [v5.1.2]
 - **BetterBibtex version: [v6.7.132]**

**Comment by sunpeng96** [comment] 2023-10-25 02:02
I had the same problem yesterday.

**Comment by Git-llong** [comment] 2023-10-25 08:38
同样的问题，还重装了mdnotes，点击创建相同的Mdnotes文件没有响应

**Comment by RoBaaaT** [comment] 2023-10-25 09:37
Hey there, I ran into the same issue this morning. It was caused by a recent update to BetterBibTex that made some naming changes. I've submitted a pull request (#225) that fixes the issue.

**Comment by sunpeng96** [comment] 2023-10-25 12:18
This is not a problem with mdnotes, it is caused by the BetterBibtex update on October 24th.
I fixed the problem by rolling back the version of BetterBibtex.

**Comment by anna1997411** [comment] 2023-10-28 09:44
I solved it, I rolled better-bibtex's version back to the old one.I choseI chose thehttps://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.77

**Comment by retorquere** [comment] 2024-01-08 12:18
> I solved it, I rolled better-bibtex's version back to the old one.I choseI chose thehttps://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.77

Please don't suggest this as a general solution. MdNotes will have to update.

**Comment by retorquere** [comment] 2024-01-08 12:33
> This is not a problem with mdnotes, it is caused by the BetterBibtex update on October 24th. 

Rather, BBT has changed, and MdNotes will have to follow.

**Comment by retorquere** [comment] 2024-01-08 12:34
And a fix for this has been available since late October previous year: #225

**Closed** 2024-10-18 11:27 UTC
Labels: bug
