### ISSUE TITLE
Use Obsidian-Citations style template for naming notes  

### ISSUE THREAD

**Issue by danieltomasz** [argenos/zotero-mdnotes#95] opened 2021-05-18 16:00 UTC
**Is your feature request related to a problem? Please describe.**

Currently, the plugin uses either citekey or title of Zotero item.
My citekys are [author][year], I would like to add the name of the article to the exported note.

**Describe the solution you'd like**

I would like to be able to specify templates similar to those used by the Citations Obsidian plugin
like 
```
@{{citekey}} {{title}}
```
or 
```
@{{citekey}} - annotations - {{title}}
```
(currently only suffic and prefix is supported)

**Additional context**

I am using the Obsidian citations plugin for creating notes where I summarise papers.

**Comment by argenos** [comment] 2021-05-18 18:17
Duplicate of #94

**Closed by argenos** 2021-05-18 18:17 UTC
Labels: enhancement
